using AutoMapper;
using BookingService.Application.Dto;
using BookingService.Domain.Entities; // Assuming your domain entities are here

namespace BookingService.Application.Mapping
{
    public class MappingConfiguration : Profile
    {
        public MappingConfiguration()
        {
            // Mapping from Domain Entity to DTO
            CreateMap<Booking, BookingDto>()
                .ForMember(dest => dest.DayIndex, opt => opt.MapFrom(src => (int)src.CheckInDate.DayOfWeek))
                .ForMember(dest => dest.StartHourIndex, opt => opt.MapFrom(src => src.CheckInDate.Hour))
                .ForMember(dest => dest.Duration, opt => opt.MapFrom(src => (src.CheckOutDate - src.CheckInDate ).TotalMinutes))
                .ForMember(dest => dest.Color, opt => opt.MapFrom(src => ColorTheme.Purple))
                .ForMember(dest => dest.Room, opt => opt.MapFrom(src => src.MeetingRoom.Description))
                .ForMember(dest => dest.Title, opt => opt.MapFrom(src => src.User.FirstName));// Map enum to string

            // Mapping from DTO to Domain Entity (for creation)
            CreateMap<CreateBookingDto, Booking>()
                .ForMember(dest => dest.Id, opt => opt.Ignore()) // ID is generated by the system
                .ForMember(dest => dest.Status, opt => opt.MapFrom(src => BookingStatus.Pending)) // Set initial booking status
                .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => DateTime.UtcNow))
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore());

            // Mapping from DTO to Domain Entity (for update)
            CreateMap<UpdateBookingDto, Booking>()
                .ForMember(dest => dest.Id, opt => opt.Ignore()) // Don't change the ID during update
                .ForMember(dest => dest.MeetingRoomId, opt => opt.Ignore()) // Assuming RoomId is not updatable via this DTO
                .ForMember(dest => dest.Status, opt => opt.Ignore()) // Status updates might be handled separately
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore()) // Don't update creation date
                .ForMember(dest => dest.UpdatedAt, opt => opt.MapFrom(src => DateTime.UtcNow));

            // Add other mappings as needed...
        }
    }
}