input {
  tcp {
    port => 5000
    # Используем json_lines и отключаем ecs_compatibility
    codec => json_lines { 
      target => "[document]"
      ecs_compatibility => disabled
    }
  }
}

filter {
  if [document] {
    ruby {
      code => "
        # Раскрываем поля из вложенного объекта в корень
        begin
          event.get('document').each {|k, v| event.set(k, v)}
          event.remove('document')
        rescue Exception => e
          event.set('ruby_error', e.message)
        end
      "
    }
  }

  # Проверяем: если поле распозналось, создаем копии. 
  # Если нет — не создаем пустые поля с текстом %{ThreadId}
  if [ThreadId] {
    mutate {
      add_field => { "thread_id" => "%{ThreadId}" }
    }
  }
  if [MachineName] {
    mutate {
      add_field => { "machine_name" => "%{MachineName}" }
    }
  }

  mutate {
    remove_field => ["port", "host"]
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}

